sudo: required
dist: trusty

# dichiarazione dipendenza mancante solamente in Travis
addons:
  apt:
    packages:
    - zip

before_install:
- chmod +x build-docs.sh build-latex.sh install-deps.sh zip-docs.sh
- "./install-deps.sh"

script:
- ./build-docs.sh a

after_success:
- ./zip-docs.sh

deploy:
  provider: releases
  api_key:
    secure: a7c460e68ae4485fa43b33c4c589fb32717fc556
  file: 
  - "Documentazione.zip"
  skip_cleanup: true
  overwrite: true
  on:
    repo: or-bit/WIP-docs

    
